# Generated by Django 3.0.3 on 2021-02-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('organization', models.CharField(max_length=256)),
                ('phone', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=1024)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
